---

- name: Edit firewalld for Grafana port
  firewalld:
    port: "{{ grafana_publish_port }}/tcp"
    permanent: true
    state: enabled
  notify: restart firewalld

- name: Create grafana storage  
  file:
    path: "{{ grafana_storage_directory }}"
    state: directory

- name: Start Grafana
  docker: 
    image: "{{ grafana_image_name }}"
    state: started
    name: "{{ grafana_container_name }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ grafana_storage_directory }}:/var/lib/grafana"
    env:
     GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
     GF_USERS_ALLOW_SIGN_UP: false
     GF_SERVER_DOMAIN: "{{ grafana_base_url }}"
    ports:
      - "{{ grafana_publish_port }}:3000"